# Dependencies
highlighter:      rouge
markdown:         kramdown
plugins:          [jekyll-archives, jekyll-paginate]

# Dependency config
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Plugin config
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag_archive
  permalinks:
    tag: /tag/:name/

# Permalinks
permalink:        pretty

# Setup
title:            Hola
tagline:          'Coffee, code and contemplation'
description:      'Thoughts on making software'
url:              https://www.louismrose.com/
baseurl:          https://www.louismrose.com/

author:
  name:           'Louis Rose'
  url:            https://twitter.com/louismrose

paginate:         5
